export default {
    SET_STATE: 'SET_STATE',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    TWEET: 'TWEET',
    GET_TWEETS: 'GET_TWEETS',
    LIKE_TWEET: 'LIKE_TWEET',
    BOOKMARK: 'BOOKMARK',
    GET_TWEET: 'GET_TWEET',
    GET_ACCOUNT: 'GET_ACCOUNT',
    GET_USER: 'GET_USER',
    GET_BOOKMARKS: 'GET_BOOKMARKS',
    UPDATE_USER: 'UPDATE_USER',
    RETWEET: 'RETWEET',
    DELETE_TWEET: 'DELETE_TWEET',
    FOLLOW_USER: 'FOLLOW_USER'

}